CREATE TABLE IF NOT EXISTS `ipol_demo_locations`
(
    `ID`                        INT(11) NOT NULL auto_increment,	
	`LOCALITY_FIAS_CODE`        CHAR(36) NOT NULL,
	`BITRIX_CODE`               VARCHAR(100) NOT NULL,
	`SYNC_IS_UPDATABLE`         CHAR(1) NOT NULL DEFAULT 'Y',
	`SYNC_LAST_DATE`            DATETIME NOT NULL,
	`SYNC_HASH`                 CHAR(32) NOT NULL,
    PRIMARY KEY (`ID`),	
	INDEX IX_IPOL_DEMO_LOCATIONS_LOCALITY_FIAS_CODE (`LOCALITY_FIAS_CODE`),
	INDEX IX_IPOL_DEMO_LOCATIONS_BITRIX_CODE (`BITRIX_CODE`),
	INDEX IX_IPOL_DEMO_LOCATIONS_SYNC_HASH (`SYNC_HASH`)
);