CREATE TABLE IF NOT EXISTS `ipol_demo_rates`
(
    `ID`                        INT(11) NOT NULL auto_increment,
	`POINT_ID`                  INT(11) UNSIGNED NOT NULL DEFAULT 0,
	`ZONE`                      VARCHAR(5) NOT NULL,
	`RATE_TYPE`                 VARCHAR(50) NOT NULL,
	`RATE_CURRENCY`             VARCHAR(3) NOT NULL,
	`RATE_VALUE`                DECIMAL(18,4) NOT NULL DEFAULT '0.0000',
	`RATE_EXTRA_VALUE`          DECIMAL(18,4) NOT NULL DEFAULT '0.0000',
	`VAT`                       DECIMAL(18,4) NOT NULL DEFAULT '0.00',
	`RATE_VALUE_WITH_VAT`       DECIMAL(18,4) NOT NULL DEFAULT '0.0000',
	`RATE_EXTRA_VALUE_WITH_VAT` DECIMAL(18,4) NOT NULL DEFAULT '0.0000',
	`SYNC_HASH`                 CHAR(32) NOT NULL,
    PRIMARY KEY (`ID`),
	INDEX IX_IPOL_DEMO_RATES_POINT_ID (`POINT_ID`),
	INDEX IX_IPOL_DEMO_RATES_SYNC_HASH (`SYNC_HASH`)
);